version: '3'
services:
  api:
    build: ./exchange-api
    ports:
    - "9000:9000"
    restart: on-failure:5
    depends_on:
      - database
  database:
    build: ./db
    ports:
    - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: exchange
      MYSQL_USER: exchangeAdmin
      MYSQL_PASSWORD: pwdAdmin