version: '3'
services:
  api:
    build: ./exchangeapi
    ports:
      - "9000:9000"
    restart: on-failure:5
    depends_on:
      - exchangedb
  exchangedb:
    build: ./db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: exchangecontrol
      MYSQL_USER: exchangecontroller
      MYSQL_PASSWORD: pwd
    cap_add:
      - SYS_NICE
